# 开发环境配置文件

# Spring配置
spring:
  datasource:
    url: jdbc:h2:file:./h2db/module;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show-sql: true
      format-sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:sql/schema.sql
      # data-locations: classpath:sql/data.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  thymeleaf:
    cache: false
logging:
  level:
    org:
      hibernate: debug
      springframework:
        web: debug